project:
  type: website
  output-dir: docs

website:
  title: "Zoe Doherty"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.html
        text: Projects
      - href: interests.html
        text: Interests
    right:
      - icon: github
        href: https://github.com/ZDoherty31
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/zoe-doherty31
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true