project:
  type: website
  output-dir: docs

website:
  title: "Zoe Doherty"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: interests.qmd
        text: Interests
      - text: Projects
        menu:
          - href: project2.html
            text: SQL Project
          - href: project3.html
            text: Text Analysis Project
    right:
      - icon: github
        href: https://github.com/ZDoherty31
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/zoe-doherty31
        aria-label: LinkedIn

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true